# env: the system of your PC (e.g. windows, macOS, Linux)
env: windows

# system: the target harmonyOS
system: harmonyOS
device: 4ABVB24930003947
#device: 23E0224307001843

package: com.dragon.read.next
keep_app: True
policy: random
count: 100
properties:
  - properties/Harmony/tomato_novel.py

# system: harmonyOS
# device: 127.0.0.1:5555
# app_path: example/orangeMall.hap
# policy: random
# count: 100
# properties: 
#   - example/example_hm_property.py
